### ISSUE TITLE
win10下使用docker安装；请求导航地址；newapi/nck/qtalk_nav.qunar，导航IP是空的

### ISSUE THREAD

**Issue by menghehe** [startalkIM/Startalk#11]
[
![1608280537(1)](https://user-images.githubusercontent.com/23393174/102592864-10805600-414f-11eb-9a5f-425305f3246f.png)
](url)

**Comment by ChaoCcWang** [comment]
./startalkdockerctl init 的时候确认一下ip是不是为空
![image](https://user-images.githubusercontent.com/54393160/102601474-2bf15e00-415b-11eb-9ccd-a658e215ebc2.png)
如果是上图这个样子, 请输入N, 然后手动输入ip
